alter table public.pedidos
  add column if not exists order_number bigint generated by default as identity;

alter table public.pedidos
  add column if not exists access_code text;

alter table public.pedidos
  add column if not exists status text;

update public.pedidos
set access_code = 'JD-' || upper(substr(replace(id::text, '-', ''), 1, 8))
where access_code is null;

update public.pedidos
set status = case
  when concluido then 'finalizado'
  when pronto_para_entrega then 'pronto'
  else 'producao'
end
where status is null;

alter table public.pedidos
  alter column access_code set not null,
  alter column status set default 'recebido',
  alter column status set not null;

create unique index if not exists pedidos_order_number_uidx
  on public.pedidos (order_number);

create unique index if not exists pedidos_access_code_uidx
  on public.pedidos (access_code);